CREATE TYPE user_role AS ENUM ('JOB_SEEKER', 'EMPLOYER', 'ADMIN');
CREATE TYPE job_status AS ENUM ('ACTIVE', 'FILLED', 'EXPIRED');
CREATE TYPE application_status AS ENUM ('PENDING', 'REVIEWED', 'REJECTED', 'ACCEPTED');
CREATE TYPE alert_frequency AS ENUM ('DAILY', 'WEEKLY');